excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://haozun.github.io
name: Lantern Dev Blog
description: migeater'blog, 0, 0);DROP DATABASE TABLICE;
author: migeater
avatar: 
ga_domain: 
ga_tracking_id: 